package com.njax.destructocats.java.webapp;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.njax.destructocats.java.app.models.HelloRepository;
import com.njax.destructocats.java.app.models.HelloEntity;

@Controller // This means that this class is a Controller
@RequestMapping(path="/hellos")
public class MainController {
    @Autowired // This means to get the bean called helloRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private HelloRepository helloRepository;


    @Autowired // https://www.vojtechruzicka.com/spring-boot-version/
    org.springframework.boot.info.BuildProperties buildProperties;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewHello (@RequestParam String title,
                                             @RequestParam String body) {
        // @ResponseBody means the returned String is the response, not a view title
        // @RequestParam means it is a parameter from the GET or POST request

        HelloEntity n = new HelloEntity();
        n.setTitle(title);
        n.setBody(body);
        helloRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<HelloEntity> getAllHellos() {
        // This returns a JSON or XML with the users
        return helloRepository.findAll();
    }

    @GetMapping(value = "")
    public ResponseEntity<Object> root() {
        String responseString = "";
        String artifactId = buildProperties.getArtifact();
        String group = buildProperties.getGroup();
        String version = buildProperties.getVersion();
        com.njax.destructocats.java.app.models.version.Version modelVersion = new com.njax.destructocats.java.app.models.version.Version();
        com.njax.destructocats.java.webapp.version.Version appVersion = new com.njax.destructocats.java.webapp.version.Version();

        responseString += "Web App: " + appVersion.info() + "<br>\n";
        responseString += "DB Models: " + modelVersion.info() + "<br>\n";

        responseString += "Count: " + helloRepository.count() + "<br>\n";
        responseString += "Cool, huh?" + "<br>\n";

        return new ResponseEntity<>(responseString, HttpStatus.OK);
    }

}
